name: Azure ARM Dev

on:
  push:
    branches: [ $default-branch ]
    paths:
      - './workflows/deployDev.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: 5dcedb53-6662-448c-bad5-9f7fb6155570
          resourceGroupName: atle_devops
          template: ./ARM-Templates/container-webapp-template.json