name: Azure ARM Dev

on:
  push:
    paths:
      - '.github/workflows/deployTest.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: 'Checkout file'
        uses: actions/checkout@v2


      - name: Run ARM deploy Test
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: atle_devops
          template: container-webapp-template.json