name: Azure ARM Dev

on:
  push:
    paths:
      - '.github/workflows/deployTest.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: atle_devops
          template: ARM-Templates/container-webapp-template.json